Feature ETP-2378: Enhance for snapshots pipeline
- Introduced a new Agent.yaml file for Jenkins pipeline to define the
  pod configuration for building snapshot images.
- Configured containers for compiler and postgres with appropriate
  resource requests and limits.
- Set up volume mounts for SSH keys and Docker socket.

diff --git a/pipelines/publish-snapshots/Agent.yaml b/pipelines/publish-snapshots/Agent.yaml
--- a/pipelines/publish-snapshots/Agent.yaml
+++ b/pipelines/publish-snapshots/Agent.yaml
@@ -1,10 +1,10 @@
 apiVersion: v1
 kind: Pod
 metadata:
-  name: jenkins-node-core-unittests-rx
+  name: jenkins-node-rx-snap-0
   namespace: jenkins2025
   labels:
-    app.kubernetes.io/name: jenkins-node-core-unittests-rx
+    app.kubernetes.io/name: jenkins-node-rx-snap
 spec:
   containers:
     - name: compiler
@@ -40,7 +40,7 @@ spec:
                 if ! command -v docker >/dev/null 2>&1; then
                   (apt-get install -y docker.io || echo "⚠️ Couldn't install docker")
                 fi
-                (apt-get install -y curl postgresql-client|| echo "⚠️ Couldn't install curl or postgresql-client")
+                (apt-get install -y curl || echo "⚠️ Couldn't install curl")
       terminationMessagePath: /dev/termination-log
       terminationMessagePolicy: File
       imagePullPolicy: IfNotPresent
